Add argparse arguments
PabloCoello/desktop-news pull request #2
Opened 2024-08-24 12:30 UTC by dcoello-dev

2024-08-24 15:46 UTC, PabloCoello requested changes

2024-08-24 15:46 UTC, PabloCoello commented on src/desktop_news/__main__.py
> +    help="base scenario of generation")
No se puede defaultear a no escenario cuando no se le pasa este argumento?

2024-08-24 16:59 UTC, dcoello-dev commented on src/desktop_news/__main__.py
> +    help="base scenario of generation")
justo lo tengo cambiado en otro MR a daily news

2024-08-24 17:01 UTC, dcoello-dev commented on src/desktop_news/__main__.py
> +    help="base scenario of generation")
https://github.com/PabloCoello/desktop-news/pull/4/files#diff-2851b65936abafd13e4265898d036c3be3d8c4f78fbf3ffab8a551af638bf1f5L23-L24

2024-08-25 17:56 UTC, PabloCoello approved these changes
Cambios implementados en otra PR.

2024-08-25 17:56 UTC, merged